### ISSUE TITLE
Lotteries should be stored in blockchain

### ISSUE THREAD

**Issue by duonghaipham** [zS1L3NT/lotterex#1]
### Tell me about the feature you are requesting!

Now the lotteries list is stored in localStorage, which means other player cannot join the lottery, so how can we have enough 3 members to start picking the winner?

**Comment by zS1L3NT** [comment]
Hi, this project was built as a school project. This means I needed to be able to customize the list of lotteries on the presentation date so that I can present the project as simply as possible to the teacher. Being able to customize the list of displayed lotteries from `localStorage` really helped me in presentation, so I not showing development/test lotteries to my teacher.

The three players in the lottery are meant to be different Ganache wallets transferring GanacheETH to Lotterex. This means that it's not actually 3 different members, it's just an admin controlling 3 different wallets to send GanacheETH to the Lotterex. This is to simulate different accounts sending ETH to Lotterex in production.

Because presentation is over and this project was used to teach me the fundamentals of using web3, I don't intend to continue this project. However, feel free to submit any pull requests! :D
